### ISSUE TITLE
Support overriding and adding environment variables 

### ISSUE THREAD

**Issue by Hobart2967** [codewyre/skwid#5]
## Acceptance Criteria

- It is possible to selectively set environment variables when running job tasks.
- It is possible to generally set environment variables when skwid.

## Example

```yaml
env:
  MY_VAR: "A_VALUE"

tasks:
  init:
    description: Initializes the repository
    jobs:
      - name: Install packages
        type: command
        command: yarn
        env: 
          FORCE_LOCAL: 1
```
